controller_manager:
  ros__parameters:
    update_rate: 30  # Hz -- mulai konservatif dulu

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    six_joint_position_controller:
      type: position_controllers/JointGroupPositionController

six_joint_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint6
      - joint7
      - joint8
    interface_name: position
